-- 1. 使用者資料表 (users)
-- 儲存所有使用者的基本資訊，並與 Supabase 的 auth.users 表格連結。
CREATE TABLE public.users (
    id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    avatar_url TEXT,
    phone_number TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 保姆資料表 (sitters)
-- 儲存保姆的專業資訊，與 users 表格一對一關聯。
CREATE TABLE public.sitters (
    id UUID NOT NULL PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    service_area TEXT, -- 服務地區
    introduction TEXT, -- 自我介紹
    price_per_hour DECIMAL(10, 2), -- 每小時價格
    is_approved BOOLEAN DEFAULT FALSE, -- 是否通過審核
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 寵物資料表 (pets)
-- 儲存使用者的寵物資訊，與 users 表格多對一關聯。
CREATE TABLE public.pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    pet_type TEXT, -- e.g., 'Dog', 'Cat'
    breed TEXT, -- 品種
    age INT,
    notes TEXT, -- 注意事項
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. 預約訂單資料表 (bookings)
-- 儲存所有服務預約的紀錄。
CREATE TYPE booking_status AS ENUM ('pending', 'confirmed', 'completed', 'cancelled');
CREATE TABLE public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    sitter_id UUID NOT NULL REFERENCES public.sitters(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES public.pets(id) ON DELETE CASCADE,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    total_price DECIMAL(10, 2),
    status booking_status DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. 評價資料表 (reviews)
-- 儲存使用者對保姆的評價。
CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE UNIQUE, -- 一個訂單只能有一則評價
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    sitter_id UUID NOT NULL REFERENCES public.sitters(id) ON DELETE CASCADE,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. 即時回報訊息資料表 (service_updates)
-- 儲存服務過程中保姆的回報訊息。
CREATE TABLE public.service_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    message TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. 保姆認證資料表 (sitter_certifications)
-- 儲存保姆的認證狀態與紀錄。
CREATE TABLE public.sitter_certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sitter_id UUID NOT NULL REFERENCES public.sitters(id) ON DELETE CASCADE UNIQUE, -- 一個保姆只有一筆認證紀錄
    certification_name TEXT NOT NULL, -- 認證名稱 (e.g., 'Pawdner 平台基礎認證')
    issued_date DATE NOT NULL, -- 頒發日期
    expiry_date DATE, -- 到期日期 (可選)
    created_at TIMESTAMPTZ DEFAULT NOW()
);